feat: Stream upload progress
rotimi-best/classroomio pull request #210
Opened 2024-03-18 17:10 UTC by Chifez

## What does this PR do?
This PR aims to improve the video upload by streaming the upload progress

Fixes # (place issue number here without bracket)

please forward to 1min 5sec to see the progress 

https://github.com/rotimi-best/classroomio/assets/69228399/90d60dcd-7573-4219-a677-e682f4e68f2f

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- run on local host,make sure your dashboard is running on port 5173

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

2024-03-22 07:48 UTC, rotimi-best commented
@Chifez Please use [supabase realtime](https://supabase.com/docs/reference/javascript/broadcastmessage) for this.

Socket.io will add an extra overhead on our backend and introduce a new package.

## Note

Make sure you pass a unique identifier for the video that is uploading to track its progress, with your current approach you are broadcasting a progress to every client connected to socketio, meaning even if two people are uploading at the same time there will be a conflict in data. Ideally use the `lessonId` to uniquely know if there is a broadcast update for that particular video upload.

### Frontend - Video upload component

```ts
let uploadChannel;

onMount(() => {
  uploadChannel = supabase.channel('upload-progress') // upload-progress is the room name you should use both on the frontend and backend
    
  uploadChannel.on('broadcast', { event: lessonId }, payload => {
    console.log('The progress of the upload', payload)
  })
});

onDestroy(() => {
  supabase.removeChannel(uploadChannel)
})
```

### Backend - /uploadVideo

```ts
supabase
  .channel('upload-progress') // upload-progress is the room name you should use both on the frontend and backend
  .subscribe((status) => {
    if (status === 'SUBSCRIBED') {
      channel.send({
        type: 'broadcast',
        event: lessonId, // This will be what we check for on the frontend
        payload: 5, // This will be the percentage progress of the upload
      })
    }
  })
```

2024-03-22 07:51 UTC, rotimi-best requested changes
Let's move away from socket.io and use supabase because it is already in our stack

2024-03-28 02:26 UTC, rotimi-best requested changes

2024-03-28 02:26 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/Materials/Video/LocalVideo.svelte
> +  const supabase = getSupabase();
You can just do this, without import getSupabase because `getSupabase` has already been called once we mount the code on the UI

```
import { supabase } from '$lib/utils/functions/supabase';
```

2024-03-28 07:15 UTC, Chifez commented on apps/dashboard/src/lib/components/Course/components/Lesson/Materials/Video/LocalVideo.svelte
> +  const supabase = getSupabase();
alright

2024-03-28 09:29 UTC, rotimi-best approved these changes
LGTM

2024-03-28 09:42 UTC, merged