feat: Certificates Update
rotimi-best/classroomio pull request #295
Opened 2024-05-01 09:47 UTC by tunny17

## What does this PR do?

Fixes #289 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- go to the /apps/backend dir then run "node server.js". Open your postman, set it up and input the params in the body and send the POST req.

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

2024-05-14 06:05 UTC, rotimi-best requested changes
Please update the branch with the latest of main and you need to fix the hard coded data

2024-05-14 06:05 UTC, rotimi-best commented on apps/backend/src/utils/certificate.js
> +      </div>
@tunny17 Lol, how will you add my name as the facilitator?

2024-05-14 06:05 UTC, rotimi-best commented on apps/backend/src/utils/certificate.js
> +        <p class="border-b-2 border-black font-bold">02,May 2024</p>
Bro, and why did you hard code date in a dynamic certificate?

2024-05-14 06:05 UTC, rotimi-best commented on apps/backend/src/utils/certificate.js
> +        </div>
Same issue with date and facilitator here.

just hide the facilitator section

2024-05-14 06:05 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Org/Settings/index.svelte
>          key: 1,
This PR looks like a mix with some translation fixes.

Please pull the latest of main into this branch

2024-05-17 17:37 UTC, rotimi-best requested changes

2024-05-17 17:37 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Ceritficate/certificates/PurpleProfessionalBadge.svelte
> +  let dateIssued = new Date().toLocaleDateString();
These should not be `let` if it isn't changing

2024-05-17 17:37 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Ceritficate/certificates/BlueProfessionalBadge.svelte
> +  let dateIssued = new Date().toLocaleDateString();
`let` issue here, please also go to the other files to update.

Also is there a reason this is within a `certificates` folder?

Please these files should be on the same level with `Design.svelte`

2024-05-17 17:37 UTC, rotimi-best commented on apps/backend/static/logo.svg
What's the purpose of this file? how is the logo shown in the other templates?

2024-05-30 18:51 UTC, rotimi-best requested changes

2024-05-30 18:51 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte
> +      });
@tunny17 Use the validation approach we use and not expose a schema to a component.

2024-07-18 02:56 UTC, rotimi-best commented
@tunny17 
- [ ] Please take a look at all certificate with Date and please make this update.

<img width="1140" alt="Screenshot 2024-07-18 at 3 51 10 AM" src="https://github.com/user-attachments/assets/83240c40-324a-42fe-9631-aeab646aec78">

- [ ] The logo and title name isn't aligned to the middle

<img width="531" alt="image" src="https://github.com/user-attachments/assets/3804532d-c0cb-4f58-a419-b68dc729d2c1">
<img width="522" alt="image" src="https://github.com/user-attachments/assets/b8985f32-4252-4942-8a18-2194d665af71">

2024-07-18 10:23 UTC, tunny17 commented
@rotimi-best  i've made the changes you requested

2024-07-19 05:17 UTC, rotimi-best approved these changes

2024-07-19 05:28 UTC, rotimi-best requested changes

2024-07-19 05:28 UTC, rotimi-best commented on apps/backend/src/utils/certificate.js
> +      src="http://localhost:3002/purple-professional-badge-background.png"
Oh damin, I didn't notice this earlier.

You should hard code a URL to localhost in your code that will be deployed to production 😢 

Please delete the static folder cause I will upload the images to cloudflare and provide you the URL.

Then delete the code:

```
// serve the images in the static folder
app.use(express.static('static'));
```

For this one use: https://assets.cdn.clsrio.com/certificates/purple-professional-badge-background.png

Then replace all the templates you have used localhost.

2024-07-21 02:02 UTC, rotimi-best approved these changes

2024-07-21 02:02 UTC, merged