feat: Grade exercises with AI
rotimi-best/classroomio pull request #296
Opened 2024-05-02 11:16 UTC by Chifez

## What does this PR do?
This PR Improves the experience for grading exercises,exercises can now be graded using AI 

Fixes #290 

https://github.com/rotimi-best/classroomio/assets/69228399/c39cf393-599a-47c6-844d-1e981b9aaf1d

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

-run on localhost

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

2024-05-06 21:36 UTC, rotimi-best requested changes
@Chifez Still a couple of things left to complete this PR.

also the migration file doesn't have any content.

2024-05-06 21:36 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte
> +          class="p-6 border-2 border-gray-300 bg-[#F5F8FE] rounded-full h-10 w-10 flex items-center justify-center text-[#2751DA] text-sm font-semibold"
I dislike custom `bg-` because they don't go well with dark mode and also from reading the code you have no clue what color it is.

2024-05-06 21:36 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/constants.js
>    }
Use translation keys for `text` here instead.

Then in the place where it is rendered make sure to wrap it around `$t`. Make sure to see how it is done in other places

2024-05-06 21:36 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/store.ts
> +export const isGradeWithAI = writable(false);
Is there a need for a custom store?

2024-05-06 21:36 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Question/RadioQuestion/index.svelte
> +              className="rounded-none py-1 px-2"
@Chifez I noticed you duplicated this logic in the 3 question component.

Can you please move it into a reusable component and it should be used in each of the question components.

2024-05-06 21:36 UTC, rotimi-best commented on apps/dashboard/src/routes/api/completion/gradingprompt/+server.js
> +
Remove this empty line

2024-05-06 21:36 UTC, rotimi-best commented on apps/dashboard/src/routes/api/completion/gradingprompt/+server.js
> +    stream: true
stream shouldn't be true

2024-05-06 21:38 UTC, rotimi-best commented
@chifez, please go over the new code to make sure everything is translated.

Change your language to French for example and then go to the UI you implemented to verify you don't have anything in english only rather in the currently selected language.

2024-05-08 20:34 UTC, Chifez commented on apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte
> +          class="p-6 border-2 border-gray-300 bg-[#F5F8FE] rounded-full h-10 w-10 flex items-center justify-center text-[#2751DA] text-sm font-semibold"
i copied it from the figma,what background color would you suggest

2024-05-10 22:02 UTC, rotimi-best approved these changes
LGTM

2024-05-10 22:03 UTC, rotimi-best commented
@Chifez Let's have a meeting on monday in the evening to discuss this PR.

2024-05-12 12:12 UTC, Chifez commented
> @Chifez Let's have a meeting on monday in the evening to discuss this PR.

alright,noted

2024-05-13 18:30 UTC, rotimi-best approved these changes
LGTM

2024-05-13 18:35 UTC, merged