fix: Fix empty lesson title bug
rotimi-best/classroomio pull request #314
Opened 2024-05-18 17:36 UTC by Chifez

## What does this PR do?
This PR fixes the empty lesson bug 

Fixes #310 

https://github.com/rotimi-best/classroomio/assets/69228399/fa4db456-c357-4e31-b3fa-0fb71a5de7be

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- run on local host

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

2024-05-19 13:27 UTC, rotimi-best requested changes

2024-05-19 13:27 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/+page.svelte
> -        </RoleBasedSecurity>
@Chifez I actually just moved this RoleBasedSecurity within CourseContainer, I missed it when testing, see the commit [here](https://github.com/rotimi-best/classroomio/commit/57cfc32dae9182cc62b9b209795839da3a13c1e1#diff-994c13a27e07a62a27d277314623ead4acb6ba3af3b00e948ad8c186bae1d2ac)


Btw that's the issue I tweeted about. Rolebasedsecurity should not be over coursecontainer because coursecontainer fetches the course and group that Rolebasedsecurity depends on to render the roles.

That's what cause this blank page on prod after i deployed the lms customization feature.

<img width="1083" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/19499b62-176b-4c3a-9ad6-9bc17279843d">

Please revert the changes in this file

2024-05-19 13:27 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/+page.svelte
> +  $: console.log('index page');
please remove

2024-05-19 13:27 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte
> +                    <span class="w-[70%] text-ellipsis line-clamp-2">{item.title}</span>
What's the reason for the 70%?

2024-05-19 13:27 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/marks/+page.svelte
> +<CourseContainer bind:courseId={data.courseId}>
@Chifez Please revert this change as well. I have fixed it on `main`

2024-05-19 13:27 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/store/lessons.ts
> +});
@Chifez I think this validation is a duplicate

2024-05-20 08:42 UTC, Chifez commented on apps/dashboard/src/routes/courses/[id]/+page.svelte
> -        </RoleBasedSecurity>
ah i see,noted

2024-05-20 08:58 UTC, Chifez commented on apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte
> +                    <span class="w-[70%] text-ellipsis line-clamp-2">{item.title}</span>
long lesson titles breaks away from the navbar, but his change makes it take up only 70% and then break into a new line
![Screenshot (1084)](https://github.com/rotimi-best/classroomio/assets/69228399/aa459c05-4888-4d07-83ed-37888ecf287d)

2024-05-20 16:25 UTC, rotimi-best approved these changes
LGTM!

2024-05-20 16:26 UTC, merged