fix: Updated the Email template
rotimi-best/classroomio pull request #351
Opened 2024-06-03 09:37 UTC by Chifez

## What does this PR do?
This PR updates the email template 

Fixes #348 

![Screenshot (1129)](https://github.com/rotimi-best/classroomio/assets/69228399/8ae7691f-5848-44f3-b2d1-c6bfe98f8e2c)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- run on local host

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

2024-06-06 20:58 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
> +          drag a card to reorder
Why is this not in translations?? 😢

2024-06-06 20:58 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
> +        {#if isSelfPaced}
@Chifez Why is this logic still here?

2024-06-06 21:03 UTC, rotimi-best requested changes
@Chifez Not sure why the reorder task is mixed with this PR.

2024-06-06 21:03 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
> +  }
No need for a function if it just toggles. Add it directly to the onClick event

2024-06-06 21:03 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
> +          drag a card to reorder
Why is this not in translations?? 😢

2024-06-06 21:03 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
> +        {#if isSelfPaced}
@Chifez Why is this logic still here?

2024-06-06 21:03 UTC, rotimi-best commented on apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
>    import PageBody from '$lib/components/PageBody/index.svelte';
@Chifez Why is the reorder change with the email template change?

2024-06-07 08:31 UTC, Chifez commented on apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
> +  }
i think i know why,i will delete now and create a new PR

2024-06-07 08:32 UTC, Chifez commented
> @Chifez Not sure why the reorder task is mixed with this PR.

I think i know why,i will delete now and create a new PR

2024-06-07 08:33 UTC, closed without merging