feat : Save functionality using enter
rotimi-best/classroomio pull request #383
Opened 2024-07-08 03:32 UTC by smritidoneria

## What does this PR do?

This pr handles the functionality of the enter key mouse event to work like submit. When the user clicks enter, the lesson title will be submitted and the dialog box will be closed.

Fixes  #373

https://github.com/rotimi-best/classroomio/assets/109029101/b75c3faa-2653-49d4-9f8d-643a7989165a

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
Go to the course
Create a lesson title and click enter, the lesson title will be submitted.
- Test B

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

2024-07-09 20:13 UTC, rotimi-best requested changes
Thanks for the work on this @smritidoneria 🤩

Please attend to the following and I can merge it in.

2024-07-09 20:13 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/NewLessonModal.svelte
> +  maxWidth="max-w-2xl "
Please can you undo this change?

2024-07-09 20:13 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/NewLessonModal.svelte
> +<form on:submit={handleSubmit} class="relative m-auto py-2 md:py-3 px-2 md:px-5 mb-2 md:mb-4 flex flex-wrap items-center dark:bg-neutral-800 bg-yellow-500">
You can change this `on:submit={handleSubmit}` to `on:submit|preventDefault={handleSave}`

and then you don't need `handleSubmit` function

2024-07-10 01:30 UTC, smritidoneria commented
hey @rotimi-best , I have committed the changes as requested, kindly review it

2024-07-10 07:12 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/NewLessonModal.svelte
> +
Please remove this extra line

2024-07-10 07:12 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/NewLessonModal.svelte
> +<!-- used form to handle enter keydown event naturally -->
Please also remove this comment

2024-07-10 07:13 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Course/components/Lesson/NewLessonModal.svelte
> +</Modal>
Please also restore the new line in this file.

2024-07-11 01:40 UTC, smritidoneria commented
hey @rotimi-best , the changes are being made. kindly look at it

2024-07-11 07:52 UTC, rotimi-best approved these changes
Great job @smritidoneria 

Thank you

2024-07-11 07:52 UTC, merged