feat: Pathway Pages UI
rotimi-best/classroomio pull request #401
Opened 2024-07-18 03:00 UTC by tunny17

## What does this PR do?
This PR Adds the course and settings page to the pathways collection of an organization.

Fixes # (CLA 54 & 56)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- add this route to your org url "/pathways/{anything, it's supposed to be the id}/"

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

[https://www.loom.com/share/749e2304cffb445ebdd21016f00db1e2?sid=74d211ef-a937-434c-ad4c-28ded7a4b28c](url)

2024-07-18 03:27 UTC, rotimi-best requested changes

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/courses/+page.svelte
> +              <StructuredListCell head>Lessons</StructuredListCell>
Please make sure your whole code supports translations

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/settings/+page.svelte
> +  }
Should be just `$: id = $page.params.id;`

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/news/+page.svelte
Newsfeed should actually be the root not its own route, please look at courses

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/lib/utils/types/index.ts
> +  courses: CollectionCourse[]
Please never use Collection to avoid confusion, replace all word `Collection` to `Pathway` for consistency.

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/lib/utils/services/courses/index.ts
> +export async function updateCollection(
Create a services folder for `pathways` and don't add pathway related functionality in the course service files

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Icons/LandingPage.svelte
All icons should come from Carbon Icons, don't download anyone

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/+layout.svelte
> +  {#if containsPathways}
Please create a function like `isQuizPage` rather than creating a variable for this.

Something like `isPathwayPage`

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/store.ts
A store file shouldn't be in the route folder.

Again please see how courses is structured

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/+page.js
> +    orgName: params.id
This should be `pathwayId` not `orgName`

2024-07-18 03:27 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/certificates/+page.svelte
> +<section class="border-2 border-black flex justify-center items-center w-full h-full">
There is a component called `CourseContainer` which is used by courses to wrap each route within `courses/[id]/*`.

Please create something like that for Pathways and use around all its nested routes

2024-07-18 12:58 UTC, tunny17 commented
@rotimi-best  i've made the fixes you requested

2024-07-19 05:07 UTC, rotimi-best approved these changes

2024-07-19 05:12 UTC, rotimi-best requested changes
@tunny17 Please always do a self code review before you submit it for review.

2024-07-19 05:12 UTC, rotimi-best commented on apps/dashboard/src/lib/components/Pathways/components/CourseCard.svelte
> +  </div>
This file is not translated

2024-07-19 05:12 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/+layout.server.ts
> +    orgName: params.id
This place still has `orgName`

2024-07-19 05:12 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/certificates/+page.svelte
> +<section class="border-2 border-black flex justify-center items-center w-full h-full">
@tunny17 what's the update with this one?

2024-07-19 05:12 UTC, rotimi-best commented on apps/dashboard/src/routes/org/[slug]/pathways/[id]/settings/+page.svelte
> +    if (!$collection.title) {
@tunny17 Please review your code naa, I have to recheck and recheck..

You are still using the word `collection`

2024-07-20 08:29 UTC, rotimi-best approved these changes
LGTM.

There are still some other things, but we can figure it out as we go

2024-07-20 08:30 UTC, merged